# Generated by Django 5.2.7 on 2025-10-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='website_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='address',
            field=models.CharField(blank=True, max_length=2048, null=True, unique=True),
        ),
    ]
